
import { ChakraProvider, Flex, Box } from '@chakra-ui/react';
import Navbar from './ui/components/Navbar';
import Footer from './ui/components/Footer'

export const metadata = {
  title: 'Ankit Balis Portfolio Website',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
  
    <html lang="en">
      <body>
       <ChakraProvider>
         <Box minHeight="100vh" display="flex" flexDirection="column">
           <Navbar />
           <Flex direction="column" flex="1">
             {children}
           </Flex>
           <Footer />
         </Box>
       </ChakraProvider>
       </body>
     
    </html>
   
  )
}
